import { createHash } from "node:crypto";
import { parseFacts } from "../memory/fence.js";
import { FsGitMemoryStore, type SourceDoc } from "../memory/store.js";
import { chunkMarkdown } from "./chunk.js";
import { getPool } from "./db.js";

export interface ChunkRecord {
  filePath: string;
  heading: string | null;
  content: string;
  contentHash: string;
}
export interface FactRecord {
  id: number;
  claim: string;
  kind: string;
  state: string;
  sourceTrust: string;
  validFrom: string | null;
  sourcePath: string;
  entitySlugs: string[];
}
export interface IndexRecords {
  chunks: ChunkRecord[];
  facts: FactRecord[];
  entities: Map<string, number>; // slug -> app-assigned id
}

/**
 * Pure: Markdown sources -> derived records (chunks/facts/entities/links). Fully testable without
 * TiDB. ids are app-assigned & stable within a full rebuild (avoids AUTO_RANDOM/JS precision —
 * poc/tidb lesson). Connections are materialized here at write time (101): facts carry entity slugs.
 */
export function buildIndexRecords(docs: SourceDoc[]): IndexRecords {
  const chunks: ChunkRecord[] = [];
  const facts: FactRecord[] = [];
  const entities = new Map<string, number>();
  let factId = 0;
  let entityId = 0;
  const ensureEntity = (slug: string): number => {
    const existing = entities.get(slug);
    if (existing !== undefined) return existing;
    const id = ++entityId;
    entities.set(slug, id);
    return id;
  };

  for (const doc of docs) {
    for (const c of chunkMarkdown(doc.content)) {
      chunks.push({
        filePath: doc.relPath,
        heading: c.heading,
        content: c.content,
        contentHash: createHash("md5").update(c.content).digest("hex"),
      });
    }
    for (const f of parseFacts(doc.content)) {
      for (const slug of f.entities) ensureEntity(slug);
      facts.push({
        id: ++factId,
        claim: f.claim,
        kind: f.kind,
        state: f.state,
        sourceTrust: f.sourceTrust,
        validFrom: f.validFrom,
        sourcePath: doc.relPath,
        entitySlugs: f.entities,
      });
    }
  }
  return { chunks, facts, entities };
}

/**
 * Full rebuild of the derived index from Markdown (docs/91 §2.4-6 invariant: DROP TiDB, `reindex`
 * restores everything). Embeddings are auto-generated by TiDB on INSERT.
 *
 * ALWAYS a full rebuild: `buildIndexRecords` assigns positional ids 1..N over the whole tree, so the
 * facts INSERT (explicit PK) only round-trips against an *empty* table. A non-truncating "incremental"
 * pass re-inserts id 1 and dies with `Duplicate entry for key facts.PRIMARY` — which silently froze the
 * index at the first reindex (every later session flush threw and never updated TiDB → recall went
 * stale). True incremental (content_hash diff, stable ids) is a later optimization; until then the
 * only correct apply is truncate-then-rebuild. `opts.all` is kept for CLI/back-compat but no longer
 * changes behavior. The brief empty-index window is acceptable for a single-user background flush.
 */
export async function reindex(_opts: { all?: boolean } = {}): Promise<void> {
  const store = new FsGitMemoryStore();
  const docs = await store.readAll();
  const rec = buildIndexRecords(docs);
  const pool = getPool();

  for (const t of ["fact_entities", "facts", "chunks", "entities"]) {
    await pool.query(`TRUNCATE TABLE ${t}`).catch(() => {}); // ignore if not migrated yet
  }
  // mention_count drives entity-resolution tie-breaks (docs/101 §5) — count references per slug.
  const mentions = new Map<string, number>();
  for (const f of rec.facts)
    for (const slug of f.entitySlugs) {
      mentions.set(slug, (mentions.get(slug) ?? 0) + 1);
    }
  for (const [slug, id] of rec.entities) {
    await pool.query(
      "INSERT INTO entities (id, slug, name, mention_count) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE name = VALUES(name), mention_count = VALUES(mention_count)",
      [id, slug, slug, mentions.get(slug) ?? 0], // TODO: real display name (currently slug); resolve in extract (101 §5)
    );
  }
  for (const c of rec.chunks) {
    await pool.query(
      "INSERT INTO chunks (file_path, heading, content, content_hash) VALUES (?,?,?,?)",
      [c.filePath, c.heading, c.content, c.contentHash],
    );
  }
  for (const f of rec.facts) {
    await pool.query(
      "INSERT INTO facts (id, claim, kind, state, source_trust, valid_from, source_path, generated_by) VALUES (?,?,?,?,?,?,?, 'extraction')",
      [f.id, f.claim, f.kind, f.state, f.sourceTrust, f.validFrom, f.sourcePath],
    );
    for (const slug of f.entitySlugs) {
      await pool.query("INSERT IGNORE INTO fact_entities (fact_id, entity_id) VALUES (?,?)", [
        f.id,
        rec.entities.get(slug),
      ]);
    }
  }
  console.log(
    `reindex: ${rec.chunks.length} chunks, ${rec.facts.length} facts, ${rec.entities.size} entities (${docs.length} docs).`,
  );
}
