import { createHash } from "node:crypto";
import { parseFacts } from "../memory/fence.js";
import { FsGitMemoryStore, type SourceDoc } from "../memory/store.js";
import { chunkMarkdown } from "./chunk.js";
import { getPool } from "./db.js";
import {
  type EntityResolver,
  buildResolver,
  canonicalizeSlug,
  loadAliasConfig,
} from "./entity-resolve.js";

export interface ChunkRecord {
  filePath: string;
  heading: string | null;
  content: string;
  contentHash: string;
}
export interface FactRecord {
  id: number;
  claim: string;
  kind: string;
  state: string;
  sourceTrust: string;
  validFrom: string | null;
  sourcePath: string;
  entitySlugs: string[]; // canonical slugs (post entity-resolution)
}
export interface EntityRecord {
  id: number;
  slug: string; // canonical
  name: string;
  kind: string;
  aliases: string[]; // observed variant slugs that merged into this node
  mentionCount: number;
  lastSeen: string | null; // max valid_from among linked facts (YYYY-MM-DD)
}
export interface IndexRecords {
  chunks: ChunkRecord[];
  facts: FactRecord[];
  entities: Map<string, number>; // canonical slug -> app-assigned id
  entityRecords: EntityRecord[];
}

/**
 * Pure: Markdown sources -> derived records (chunks/facts/entities/links). Fully testable without
 * TiDB. ids are app-assigned & stable within a full rebuild (avoids AUTO_RANDOM/JS precision —
 * poc/tidb lesson). Connections are materialized here at write time (101): facts carry entity slugs.
 *
 * `resolver` canonicalizes entity slugs (docs/101 §5): variant spellings collapse to one node, and
 * the observed variants are recorded as `aliases`. Defaults to a format-only resolver.
 */
export function buildIndexRecords(
  docs: SourceDoc[],
  resolver: EntityResolver = buildResolver(null),
): IndexRecords {
  const chunks: ChunkRecord[] = [];
  const facts: FactRecord[] = [];
  const entities = new Map<string, number>();
  const recs = new Map<string, EntityRecord & { aliasSet: Set<string> }>();
  let factId = 0;
  let entityId = 0;
  const ensureEntity = (canon: string): EntityRecord & { aliasSet: Set<string> } => {
    const existing = recs.get(canon);
    if (existing) return existing;
    const id = ++entityId;
    entities.set(canon, id);
    const m = resolver.meta(canon);
    const rec = {
      id,
      slug: canon,
      name: m.name,
      kind: m.kind,
      aliases: [] as string[],
      aliasSet: new Set<string>(),
      mentionCount: 0,
      lastSeen: null as string | null,
    };
    recs.set(canon, rec);
    return rec;
  };

  for (const doc of docs) {
    for (const c of chunkMarkdown(doc.content)) {
      chunks.push({
        filePath: doc.relPath,
        heading: c.heading,
        content: c.content,
        contentHash: createHash("md5").update(c.content).digest("hex"),
      });
    }
    for (const f of parseFacts(doc.content)) {
      const resolved: string[] = [];
      const seen = new Set<string>();
      for (const raw of f.entities) {
        const canon = resolver.resolve(raw);
        if (!canon) continue;
        const rec = ensureEntity(canon);
        const normRaw = canonicalizeSlug(raw);
        if (normRaw && normRaw !== canon) rec.aliasSet.add(normRaw); // remember the variant we merged
        if (!seen.has(canon)) {
          seen.add(canon);
          resolved.push(canon);
          rec.mentionCount++;
          if (f.validFrom && (!rec.lastSeen || f.validFrom > rec.lastSeen))
            rec.lastSeen = f.validFrom;
        }
      }
      facts.push({
        id: ++factId,
        claim: f.claim,
        kind: f.kind,
        state: f.state,
        sourceTrust: f.sourceTrust,
        validFrom: f.validFrom,
        sourcePath: doc.relPath,
        entitySlugs: resolved,
      });
    }
  }
  const entityRecords: EntityRecord[] = [...recs.values()].map((r) => ({
    id: r.id,
    slug: r.slug,
    name: r.name,
    kind: r.kind,
    aliases: [...r.aliasSet],
    mentionCount: r.mentionCount,
    lastSeen: r.lastSeen,
  }));
  return { chunks, facts, entities, entityRecords };
}

/**
 * Full rebuild of the derived index from Markdown (docs/91 §2.4-6 invariant: DROP TiDB, `reindex`
 * restores everything). Embeddings are auto-generated by TiDB on INSERT.
 *
 * ALWAYS a full rebuild: `buildIndexRecords` assigns positional ids 1..N over the whole tree, so the
 * facts INSERT (explicit PK) only round-trips against an *empty* table. A non-truncating "incremental"
 * pass re-inserts id 1 and dies with `Duplicate entry for key facts.PRIMARY` — which silently froze the
 * index at the first reindex (every later session flush threw and never updated TiDB → recall went
 * stale). True incremental (content_hash diff, stable ids) is a later optimization; until then the
 * only correct apply is truncate-then-rebuild. `opts.all` is kept for CLI/back-compat but no longer
 * changes behavior. The brief empty-index window is acceptable for a single-user background flush.
 */
export async function reindex(_opts: { all?: boolean } = {}): Promise<void> {
  const store = new FsGitMemoryStore();
  const docs = await store.readAll();
  const resolver = buildResolver(await loadAliasConfig(store.root));
  const rec = buildIndexRecords(docs, resolver);
  const pool = getPool();

  for (const t of ["fact_entities", "facts", "chunks", "entities"]) {
    await pool.query(`TRUNCATE TABLE ${t}`).catch(() => {}); // ignore if not migrated yet
  }
  // Entity nodes carry canonical slug + display name + kind + merged aliases + mention_count
  // + last_seen (docs/101 §5). mention_count drives entity-resolution tie-breaks.
  for (const e of rec.entityRecords) {
    await pool.query(
      `INSERT INTO entities (id, slug, name, kind, aliases, mention_count, last_seen)
       VALUES (?,?,?,?,?,?,?)
       ON DUPLICATE KEY UPDATE name=VALUES(name), kind=VALUES(kind), aliases=VALUES(aliases),
         mention_count=VALUES(mention_count), last_seen=VALUES(last_seen)`,
      [e.id, e.slug, e.name, e.kind, JSON.stringify(e.aliases), e.mentionCount, e.lastSeen],
    );
  }
  for (const c of rec.chunks) {
    await pool.query(
      "INSERT INTO chunks (file_path, heading, content, content_hash) VALUES (?,?,?,?)",
      [c.filePath, c.heading, c.content, c.contentHash],
    );
  }
  for (const f of rec.facts) {
    await pool.query(
      "INSERT INTO facts (id, claim, kind, state, source_trust, valid_from, source_path, generated_by) VALUES (?,?,?,?,?,?,?, 'extraction')",
      [f.id, f.claim, f.kind, f.state, f.sourceTrust, f.validFrom, f.sourcePath],
    );
    for (const slug of f.entitySlugs) {
      await pool.query("INSERT IGNORE INTO fact_entities (fact_id, entity_id) VALUES (?,?)", [
        f.id,
        rec.entities.get(slug),
      ]);
    }
  }
  console.log(
    `reindex: ${rec.chunks.length} chunks, ${rec.facts.length} facts, ${rec.entities.size} entities (${docs.length} docs).`,
  );
}
